import { ResourceProps } from '@refinedev/core';
import { ROUTES } from '@/routes';

// Define all resources for Refine
export const resources: ResourceProps[] = [
  {
    name: 'dashboard',
    list: ROUTES.dashboard,
    meta: {
      label: 'Dashboard',
      icon: 'DashboardOutlined',
    },
  },
  {
    name: 'companies',
    list: ROUTES.admin.companies.list,
    create: ROUTES.admin.companies.create,
    edit: ROUTES.admin.companies.edit,
    show: ROUTES.admin.companies.show,
    meta: {
      label: 'Companies',
      icon: 'BankOutlined',
      canDelete: true,
    },
  },
  {
    name: 'offices',
    list: ROUTES.admin.offices.list,
    create: ROUTES.admin.offices.create,
    edit: ROUTES.admin.offices.edit,
    show: ROUTES.admin.offices.show,
    meta: {
      label: 'Offices',
      icon: 'ShopOutlined',
      canDelete: true,
    },
  },
  {
    name: 'departments',
    list: ROUTES.admin.departments.list,
    create: ROUTES.admin.departments.create,
    edit: ROUTES.admin.departments.edit,
    show: ROUTES.admin.departments.show,
    meta: {
      label: 'Departments',
      icon: 'ApartmentOutlined',
      canDelete: true,
    },
  },
  {
    name: 'positions',
    list: ROUTES.admin.positions.list,
    create: ROUTES.admin.positions.create,
    edit: ROUTES.admin.positions.edit,
    show: ROUTES.admin.positions.show,
    meta: {
      label: 'Positions',
      icon: 'IdcardOutlined',
      canDelete: true,
    },
  },
  {
    name: 'employees',
    list: ROUTES.admin.employees.list,
    create: ROUTES.admin.employees.create,
    edit: ROUTES.admin.employees.edit,
    show: ROUTES.admin.employees.show,
    meta: {
      label: 'Employees',
      icon: 'UserOutlined',
      canDelete: true,
    },
  },
  {
    name: 'vehicles',
    list: ROUTES.admin.vehicles.list,
    create: ROUTES.admin.vehicles.create,
    edit: ROUTES.admin.vehicles.edit,
    show: ROUTES.admin.vehicles.show,
    meta: {
      label: 'Vehicles',
      icon: 'CarOutlined',
      canDelete: true,
    },
  },
  {
    name: 'trips',
    list: ROUTES.admin.trips.list,
    create: ROUTES.admin.trips.create,
    edit: ROUTES.admin.trips.edit,
    show: ROUTES.admin.trips.show,
    meta: {
      label: 'Trips',
      icon: 'RouteOutlined',
      canDelete: true,
    },
  },
  {
    name: 'customers',
    list: ROUTES.admin.customers.list,
    create: ROUTES.admin.customers.create,
    edit: ROUTES.admin.customers.edit,
    show: ROUTES.admin.customers.show,
    meta: {
      label: 'Customers',
      icon: 'TeamOutlined',
      canDelete: true,
    },
  },
  {
    name: 'drivers',
    list: ROUTES.admin.drivers.list,
    create: ROUTES.admin.drivers.create,
    edit: ROUTES.admin.drivers.edit,
    show: ROUTES.admin.drivers.show,
    meta: {
      label: 'Drivers',
      icon: 'CarOutlined',
      canDelete: true,
    },
  },
  {
    name: 'invoices',
    list: ROUTES.admin.invoices.list,
    create: ROUTES.admin.invoices.create,
    edit: ROUTES.admin.invoices.edit,
    show: ROUTES.admin.invoices.show,
    meta: {
      label: 'Invoices',
      icon: 'FileTextOutlined',
      canDelete: true,
    },
  },
  {
    name: 'vehicle_assignments',
    list: ROUTES.admin.vehicle_assignments.list,
    create: ROUTES.admin.vehicle_assignments.create,
    edit: ROUTES.admin.vehicle_assignments.edit,
    show: ROUTES.admin.vehicle_assignments.show,
    meta: {
      label: 'Vehicle assignments',
      icon: 'DeploymentUnitOutlined',
      canDelete: true,
    },
  },
  {
    name: 'vehicle_expenses',
    list: ROUTES.admin.vehicle_expenses.list,
    create: ROUTES.admin.vehicle_expenses.create,
    edit: ROUTES.admin.vehicle_expenses.edit,
    show: ROUTES.admin.vehicle_expenses.show,
    meta: {
      label: 'Vehicle expenses',
      icon: 'WalletOutlined',
      canDelete: true,
    },
  },
  {
    name: 'allowances',
    list: ROUTES.admin.allowances.list,
    create: ROUTES.admin.allowances.create,
    edit: ROUTES.admin.allowances.edit,
    show: ROUTES.admin.allowances.show,
    meta: {
      label: 'Allowances',
      icon: 'GiftOutlined',
      canDelete: true,
    },
  },
  {
    name: 'deductions',
    list: ROUTES.admin.deductions.list,
    create: ROUTES.admin.deductions.create,
    edit: ROUTES.admin.deductions.edit,
    show: ROUTES.admin.deductions.show,
    meta: {
      label: 'Deductions',
      icon: 'MinusCircleOutlined',
      canDelete: true,
    },
  },
  {
    name: 'attendances',
    list: ROUTES.admin.attendances.list,
    create: ROUTES.admin.attendances.create,
    edit: ROUTES.admin.attendances.edit,
    show: ROUTES.admin.attendances.show,
    meta: {
      label: 'Attendance',
      icon: 'CalendarOutlined',
      canDelete: true,
    },
  },
  {
    name: 'payrolls',
    list: ROUTES.admin.payrolls.list,
    create: ROUTES.admin.payrolls.create,
    edit: ROUTES.admin.payrolls.edit,
    show: ROUTES.admin.payrolls.show,
    meta: {
      label: 'Payrolls',
      icon: 'DollarOutlined',
      canDelete: false,
    },
  },
  {
    name: 'reports',
    list: ROUTES.admin.reports.list,
    meta: {
      label: 'Reports',
      icon: 'FileTextOutlined',
    },
  },
  {
    name: 'users',
    list: ROUTES.admin.users.list,
    create: ROUTES.admin.users.create,
    edit: ROUTES.admin.users.edit,
    show: ROUTES.admin.users.show,
    meta: {
      label: 'Users',
      icon: 'TeamOutlined',
      canDelete: true,
    },
  },
  {
    name: 'roles',
    list: ROUTES.admin.roles.list,
    create: ROUTES.admin.roles.create,
    edit: ROUTES.admin.roles.edit,
    show: ROUTES.admin.roles.show,
    meta: {
      label: 'Roles',
      icon: 'SafetyOutlined',
      canDelete: true,
    },
  },
];
