export type CompanyStatus = 'active' | 'inactive';
export type CustomerType = 'individual' | 'company';
export type VehicleType = 'truck' | 'van' | 'car' | 'motorcycle';
export type VehicleStatus = 'active' | 'maintenance' | 'inactive' | 'broken' | 'out_of_service';
export type { TripStatus } from '@/utils/tripStatus';
export type InvoiceStatus = 'draft' | 'issued' | 'paid' | 'cancelled';
export type LeaveStatus = 'pending' | 'approved' | 'rejected' | 'cancelled';
export type UserStatus = 'active' | 'inactive';
export type ChatTask = 'chat' | 'classify' | 'extract' | 'advice';
export type NotificationType = 'create' | 'update' | 'delete' | 'system' | 'user';
export type DispatchTripStatus = 'pending' | 'assigned' | 'in_transit' | 'delivered' | 'completed' | 'cancelled';
